# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
    environment:
      CI: true
    steps:
      - checkout
      - run: npm run build
      - run:
          command: npm run test
          no_output_timeout: 300m
